"""Create branch, commit generated files, open MR, and post issue comment."""

from __future__ import annotations

import logging
import re
from typing import TYPE_CHECKING

from forgeproof.gitlab.api import GitLabAPI

if TYPE_CHECKING:
    from forgeproof.models import RunState
    from forgeproof.config import ForgeProofConfig

log = logging.getLogger(__name__)

_MR_TEMPLATE = """\
## ForgeProof — AI-Generated Changes

**Run ID:** `{run_id}`
**Issue:** #{issue_iid}
**Review-ready:** {review_ready}

### Evaluation Summary

| Gate | Result |
|------|--------|
| Deterministic checks | {determ_status} |
| Requirements coverage | {coverage:.0f}% (threshold: {threshold:.0f}%) |
{gate_rows}

### Generated Files

{file_list}

### Provenance

A signed `.rpack` provenance bundle is attached as a job artifact.
Run `forgeproof verify <pack.rpack>` to verify offline.

{pack_info}

---
*Generated by [ForgeProof](https://gitlab.com) — AI agent with tamper-evident provenance*
"""

_COMMENT_TEMPLATE = """\
### ForgeProof Results

**Run:** `{run_id}`
**Review-ready:** {review_emoji} {review_ready}

| Metric | Value |
|--------|-------|
| Requirements coverage | {coverage:.0f}% |
| Gate failures | {gate_count} |
| Generated files | {file_count} |

{gate_details}

**MR:** {mr_link}

<details>
<summary>Generated files</summary>

{file_list}

</details>
"""


def slugify(text: str) -> str:
    """Convert text to a branch-safe slug."""
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower().strip())
    return slug.strip("-")[:50]


def create_branch_name(issue_iid: int, title: str) -> str:
    return f"forgeproof/{issue_iid}-{slugify(title)}"


def run_mr_flow(
    config: ForgeProofConfig,
    state: RunState,
) -> dict:
    """Execute the full MR creation flow. Returns MR data dict."""
    if not config.gitlab_token:
        log.warning("No GitLab token available — skipping MR creation")
        return {}

    if not config.project_id:
        log.warning("No CI_PROJECT_ID — skipping MR creation")
        return {}

    api = GitLabAPI(config.gitlab_base_url, config.gitlab_token)
    pid = config.project_id

    # 1. Create branch
    branch = create_branch_name(state.issue.issue_iid, state.issue.issue_title)
    state.git.work_branch = branch

    if not api.branch_exists(pid, branch):
        api.create_branch(pid, branch, ref=state.git.base_branch)
    else:
        log.info("Branch %s already exists, reusing", branch)

    # 2. Commit generated files
    if state.file_changes:
        actions = []
        for fc in state.file_changes:
            # Use "create" for new files, "update" for modifications
            action = "create" if fc.action == "create" else "update"
            actions.append({
                "action": action,
                "file_path": fc.path,
                "content": fc.content,
            })

        commit_msg = (
            f"feat: ForgeProof generated changes for #{state.issue.issue_iid}\n\n"
            f"Run ID: {state.run_id}\n"
            f"Issue: {state.issue.issue_title}\n"
            f"Files: {len(state.file_changes)}"
        )
        commit = api.create_commit(pid, branch, commit_msg, actions)
        state.git.head_commit = commit.get("id", "")
        log.info("Committed %d files: %s", len(actions), commit.get("id", "")[:12])

    # 3. Create merge request
    is_draft = state.evaluation is not None and not state.evaluation.review_ready
    mr_description = _build_mr_description(state)

    mr_title = f"[ForgeProof] {state.issue.issue_title}"
    mr = api.create_merge_request(
        pid,
        source_branch=branch,
        target_branch=state.git.base_branch,
        title=mr_title,
        description=mr_description,
        draft=is_draft,
        labels="forgeproof,ai-generated",
    )

    mr_url = mr.get("web_url", "")
    log.info("MR created: %s (draft=%s)", mr_url, is_draft)

    # 4. Post comment on issue
    if state.issue.issue_iid:
        comment = _build_issue_comment(state, mr_url)
        try:
            api.post_issue_comment(pid, state.issue.issue_iid, comment)
        except Exception:
            log.warning("Failed to post issue comment", exc_info=True)

    return mr


def _build_mr_description(state: RunState) -> str:
    ev = state.evaluation
    if ev:
        determ = "PASS" if ev.deterministic_pass else "FAIL"
        gate_rows = ""
        for gf in ev.gate_failures:
            gate_rows += f"| {gf} | FAIL |\n"
        if not gate_rows:
            gate_rows = "| All gates passed | PASS |\n"
        coverage = ev.requirements_coverage
        threshold = 80.0  # default
    else:
        determ = "N/A"
        gate_rows = "| (no evaluation) | — |\n"
        coverage = 0.0
        threshold = 80.0

    file_list = "\n".join(
        f"- `{fc.path}` ({fc.action}, {len(fc.content)} chars)"
        for fc in state.file_changes
    ) or "_(none)_"

    pack_info = f"Pack path: `{state.pack_path}`" if state.pack_path else ""

    return _MR_TEMPLATE.format(
        run_id=state.run_id,
        issue_iid=state.issue.issue_iid,
        review_ready=ev.review_ready if ev else "N/A",
        determ_status=determ,
        coverage=coverage,
        threshold=threshold,
        gate_rows=gate_rows,
        file_list=file_list,
        pack_info=pack_info,
    )


def _build_issue_comment(state: RunState, mr_url: str) -> str:
    ev = state.evaluation

    review_ready = ev.review_ready if ev else False
    review_emoji = "✅" if review_ready else "⚠️"
    coverage = ev.requirements_coverage if ev else 0.0
    gate_count = len(ev.gate_failures) if ev else 0

    gate_details = ""
    if ev and ev.gate_failures:
        gate_details = "**Gate failures:**\n" + "\n".join(f"- {g}" for g in ev.gate_failures)

    file_list = "\n".join(
        f"- `{fc.path}` ({fc.action})" for fc in state.file_changes
    ) or "_(none)_"

    mr_link = f"[{mr_url}]({mr_url})" if mr_url else "_(not created)_"

    return _COMMENT_TEMPLATE.format(
        run_id=state.run_id,
        review_emoji=review_emoji,
        review_ready=review_ready,
        coverage=coverage,
        gate_count=gate_count,
        file_count=len(state.file_changes),
        gate_details=gate_details,
        mr_link=mr_link,
        file_list=file_list,
    )
